apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    apps: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: hello
  template:
    metadata:
      labels:
        apps: hello
    spec:
      containers:
        - name: my- container
          image: nginx
          ports:
            - containerPort: 80


      
