apiVersion: apps/v1
kind: deployment
metadata:
  name: nginx-deployment
  labels:
    apps: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: hello
  templete:
    metadata:
      labels:
        apps:hello
    spec:
      containers:
        - name:
          image:
          ports:
            - containerPort: 80


      
