apiversion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    apps: hello
  ports:
    - protocol: TCP
      port: 80  # port exposed by service
      targetPort: # container port in pod
  type: ClusterIP